const Discord = require('discord.js');
module.exports = new Discord.MessageEmbed()
    .setColor('#0099ff')
    .setTitle('World Trigger Bot')
    .setURL('https://discord.gg/WvbBzgS')
    .setAuthor('Emperor Bob#7598', 'https://cdn.discordapp.com/avatars/259841719141531649/335b106a9086e638167d4f30ffaef5fa.webp', 'https://emperorbob7.github.io/')
    .setDescription('Commands')
    .setThumbnail('https://cdn.discordapp.com/avatars/259841719141531649/335b106a9086e638167d4f30ffaef5fa.webp')
    .addField('b!help', 'This Message lol', false)
    .addField('b!level', 'Sends you your Mee6 Exp', false)
    .addField('b!roll', 'Shows help for the roll command.', false)
    .addField('b!selectStarter {Yuma, Chika, Jin, Osamu}', 'Select your starter gacha character (all 1*).', false)
    .addField('b!register', 'Register yourself in the Database', false)
    .setTimestamp()